### ISSUE TITLE
Any plans to upgrade to date-fns-2 ?

### ISSUE THREAD

**Issue by bootleg-icarus** [mcibique/vue-date-fns#5]
It's been a while since it came out. I'm not even sure if upgrading has any significant gains but I just wanna know your plans for this wrapper

**Comment by mcibique** [comment]
Hi @bootleg-icarus,

I've been playing with alpha version of date-fns v2 long time ago, but I saw lots of breaking changes everywhere, so I postponed the release until it's stable and then I completely forgot to publish it. It should be out now: `npm install vue-date-fns@2 --save`. I created major release because of all breaking changes in `date-fns`.

Let me know if it's working, and be careful with upgrading because `date-fns@2` has lots of breaking changes, especially because of changes in format API: https://date-fns.org/v2.14.0/docs/format#v2.0.0-breaking-changes. 

I haven't tested it in any live project, only made sure all tests were passing.
