### ISSUE TITLE
TypeError: formatDate is not a function

### ISSUE THREAD

**Issue by hjelperne** [mcibique/vue-date-fns#6]
Hi,
In my main.js I used to have (with version 1):

```
import {createDateFilter} from "vue-date-fns";
import locale from "date-fns/locale/nb";
...
Vue.filter("fullDateTime", createDateFilter("DD.MM.YYYY HH:mm:ss", {locale}));
```

After updating to version 2.0.0 of vue-date-fns I updated the format to:

`Vue.filter("fullDateTime", createDateFilter("dd.MM.yyyy HH:mm:ss", {locale}));`

Now I keep getting in console:
 "vue.runtime.esm.js?2b0e:619 [Vue warn]: Error in render: "TypeError: formatDate is not a function""

with a reference to the  index.js of the vue-date-fns package: 

```
var formatDate = require("date-fns/format"); 

// https://date-fns.org/v2.14.0/docs/format#v2.0.0-breaking-changes
var DEFAULT_DATE_FORMAT = "yyyy-MM-dd'T'HH:mm:ss.SSSxxx";

function createDateFilter (defaultFormat, defaultOptions) {
  return function dateFilter (date, format, opts) {
    if (!date) {
      return "";
    }
    return formatDate(date, format || defaultFormat || DEFAULT_DATE_FORMAT, Object.assign({}, defaultOptions || {}, opts));
  };
}
```

Any suggestions what I might be doing wrong?

**Comment by mcibique** [comment]
Hi @hjelperne, thanks for reporting. I fixed the problem in v2.0.1. Give it a try.

The issue was in the import:
```js
var formatDate = require("date-fns/format"); 
```
... which worked fine with v1 `date-fns` but in v2, they started to support ESM too and that broke it when you try to build the app using `@vue/cli` for example. From now, the import on ESM build must be done like this;
```js
var formatDate = require("date-fns/format").default; 
```

I fixed it and now it should always works regardless if it's `commonjs` or `ESM` build.
